### ISSUE TITLE
CSS asset not loading due to Kirby 2.3 beta bug

### ISSUE THREAD

**Issue by distantnative** [distantnative/oembed#46]
See: https://github.com/getkirby/kirby/issues/441

# Temporary fix
Instead of linking the plugin's file simply include the following CSS code in your own CSS file:

```css
.kirby-plugin-oembed{position:relative;padding:0}.kirby-plugin-oembed img{display:block;height:auto}.kirby-plugin-oembed--video iframe,.kirby-plugin-oembed--video object,.kirby-plugin-oembed__thumb{top:0;left:0;width:100%;height:100%;position:absolute}.kirby-plugin-oembed--video{background-color:#ddd;overflow:hidden}.kirby-plugin-oembed--error{font-size:.8em}.kirby-plugin-oembed__thumb{background-repeat:no-repeat;background-position:center center;background-size:cover;cursor:pointer;z-index:10}.kirby-plugin-oembed__thumb>img{position:absolute;top:50%;left:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);-webkit-transition:opacity .4s ease-in-out;transition:opacity .4s ease-in-out;opacity:.7}.kirby-plugin-oembed__thumb:hover>img{opacity:1}
```
